### ISSUE TITLE
Could you provide Windows builds too?

### ISSUE THREAD

**Issue by 3oheicrw** [noobsoftware/silver2#1]
Normal Windows builds for Windows 7 64 bit and above. On Windows XP we already have roytam1's builds.

**Comment by noobsoftware** [comment]
I can look into it, I am using this repo as my source for Silver: https://repo.palemoon.org/andkrau/Basilisk It is my understanding he is doing windows builds using the branding: Nightlizard. I'm not sure where to download it.

**Comment by 3oheicrw** [comment]
> https://nightlizard.libinfo.science/

His builds are automated build and is always in alpha quality as he said. It's quite different from your version.

**Comment by 3oheicrw** [comment]
> I can look into it, I am using this repo as my source for Silver: https://repo.palemoon.org/andkrau/Basilisk It is my understanding he is doing windows builds using the branding: Nightlizard. I'm not sure where to download it.

Currently only roytam1 provided Basilisk based browsers build for Windows even though he target Windows XP only. The Windows XP only part is a problem. Many users are running Windows 7 64 bit and above. So having a Basilisk optimized specially for this target is much better than reusing roytam1's builds for Windows XP.

**Comment by noobsoftware** [comment]
I understand, i would like to release builds for both windows and mac the only problem is I only have a windows virtual machine with limited ram and disk space and the build process requires installing lots of stuff like an older version of Visual Studio, if someone has a windows machine and is interested in building Silver, feel free to do so. I can perhaps look into it in the future.

**Comment by 3oheicrw** [comment]
> I understand, i would like to release builds for both windows and mac the only problem is I only have a windows virtual machine with limited ram and disk space and the build process requires installing lots of stuff like an older version of Visual Studio, if someone has a windows machine and is interested in building Silver, feel free to do so. I can perhaps look into it in the future.

Well. I understand.
